apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloudnative-pg
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  channel: stable-v1
  installPlanApproval: {{ .Values.installPlanApproval | default "Manual" }}
  name: cloudnative-pg
  source: certified-operators
  sourceNamespace: openshift-marketplace