global:
  clusterBaseUrl: ''
  serviceCABundle: ''

installPlanApproval: Manual
rhclVersion: rhcl-operator.v1.4.2

maasIngressCertSecret: cert-manager-ingress-cert
maasRoute: false
maasRouteConfig:
  termination: passthrough

maasDb:
  certificateIssuer:
    name: ca-issuer
    kind: ClusterIssuer
  storage:
    size: 2Gi
