apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-ai-americas/rhoai-argo.git
    path: argocd-applications
    targetRevision: main
    helm:
      valuesObject:
        installPlanApproval: Manual
        configuration:
          gpuApp:
            nvidiaGpuChannel: "v25.10"
            nvidiaGpuVersion: 'gpu-operator-certified.v25.10.1'
            nvidiaGpuDriverVersion: 580.126.20
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated: {}
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true