apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-app-of-apps
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-ai-americas/rhoai-argo.git
    path: argocd-applications
    targetRevision: maas
    helm:
      valuesObject:
        global:
          clusterBaseUrl: ''
          serviceCABundle: ''
        installPlanApproval: Manual
        enableGpuApp: true
        enableInferenceApp: true
        enableInfrastructureApp: true
        enableObservabilityApp: true
        enableRhoaiApp: true
        enableWorkloadScalingApp: true
        enableSelfSignedCertsApp: true
        externalDatabase: &externalDatabase false
        configuration:
          inferenceApp:
            maasIngressCertSecret: cert-manager-ingress-cert
            rhclVersion: rhcl-operator.v1.4.3
            maasRoute: true
          gpuApp:
            nvidiaGpuChannel: "stable"
            nvidiaGpuVersion: 'gpu-operator-certified.v26.7.0'
            nvidiaGpuDriverVersion: 615.71.09
          rhoaiApp:
            externalDatabase: *externalDatabase
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated: {}
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true