apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-deployment
spec:
  destination:
    name: in-cluster
    namespace: test
  source:
    path: helm/parent
    repoURL: https://github.com/brianjball/rhoai-argo.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops