apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-deployment
spec:
  destination:
    name: in-cluster
    namespace: default
  source:
    path: helm/
    repoURL: https://github.com/redhat-ai-americas/rhoai-argo.git
    targetRevision: HEAD
    helm:
      parameters:
        - name: channel
          value: fast
        - name: dashboardConfig.disableModelCatalog
          value: "false"
        - name: dashboardConfig.disableHardwareProfiles
          value: "false"
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops