{{- if eq .Values.advancedServing "Managed" }}
apiVersion: v1
kind: Namespace
metadata:
  name: authorino-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: authorino-operator-group
  namespace: authorino-operator
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: authorino-operator
  namespace: authorino-operator
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: authorino-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
{{- end }}