{{- if not (or (eq .Values.maasDb.enableMaas "Removed") .Values.externalDatabase) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-maas-db-config
  namespace: maas-db
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
{{- end }}