{{- if not (eq .Values.maasDb.enableMaas "Removed") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-maas-db-config
  namespace: maas-db
  annotations:
    argocd.argoproj.io/sync-wave: "40"
{{- end }}