{{- if .Values.enableMaasApp }}
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaasTenantConfig
metadata:
  name: default-tenant
  namespace: models-as-a-service
  annotations:
    argocd.argoproj.io/sync-wave: "42"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,ServerSideApply=true
spec:
  telemetry:
    enabled: {{ .Values.enableObservabilityApp }}
    metrics:
      captureOrganization: true
      captureUser: true
      captureGroup: false
      captureModelUsage: true
{{- end }}