apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-default-gateway-config
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "16"
data:
  deployment: |
    spec:
      template:
        spec:
          containers:
          - name: istio-proxy
            resources:
                limits:
                  cpu: "2"
                  memory: 2Gi
                requests:
                  cpu: 100m
                  memory: 256Mi