global:
  toolsImage: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
  clusterBaseUrl: ''

installPlanApproval: &installPlanApproval Manual
kueue: &kueue "Unmanaged"
trainer: &trainer "Managed"
spark: &spark "Managed"
maas: &maas "Managed"
externalDatabase: &externalDatabase true

enableGpuApp: true
enableInferenceApp: true
enableInfrastructureApp: true
enableObservabilityApp: true
enableRhoaiApp: true
enableWorkloadScalingApp: true
addSelfSignedCerts: false

configuration:
  databaseApp:
    installPlanApproval: *installPlanApproval
    maasDb:
      enableMaas: *maas
      storage:
        size: 2Gi
        storageClass: gp3-csi

  gpuApp:
    installPlanApproval: *installPlanApproval
    enableRdma: false
    nvidiaGpuChannel: "v25.3"
    nvidiaGpuVersion: 'gpu-operator-certified.v25.3.0'
    nvidiaGpuDriverVersion: 575.57.08

  inferenceApp:
    installPlanApproval: *installPlanApproval
    rhclVersion: rhcl-operator.v1.3.4
    certManagerCertSecret: cert-manager-ingress-cert

  infrastructureApp:
    installPlanApproval: *installPlanApproval

  observabilityApp:
    installPlanApproval: *installPlanApproval
    cooVersion: cluster-observability-operator.v1.4.0

  rhoaiApp:
    externalDatabase: *externalDatabase
    installPlanApproval: Manual

    operatorReplicas: 1
    dashboardReplicas: 1

    dataScienceClusterInitialization:
      monitoring:
        managementState: Managed
        namespace: redhat-ods-monitoring
        metrics:
          storage:
            size: 5Gi
            retention: 1d

    dataScienceCluster:
      create: true

      components:
        sparkoperator:
          managementState: *spark
        kserve:
          managementState: Managed
          nim:
            managementState: Managed
          rawDeploymentServiceConfig: Headed
          modelsAsService:
            managementState: *maas
        modelregistry:
          managementState: Managed
          registriesNamespace: rhoai-model-registries
        feastoperator:
          managementState: Managed
        trustyai:
          managementState: Managed
        aipipelines:
          managementState: Managed
          argoWorkflowsControllers:
            managementState: Managed
        ray:
          managementState: Managed
        kueue:
          defaultClusterQueueName: default
          defaultLocalQueueName: default
          managementState: *kueue
        workbenches:
          managementState: Managed
          workbenchNamespace: rhods-notebooks
        dashboard:
          managementState: Managed
        mlflowoperator:
          managementState: Managed
        trainer:
          managementState: *trainer
        trainingoperator:
          managementState: Removed
        llamastackoperator:
          managementState: Managed

    userGroups:
      - system:authenticated

    dashboardConfig:
      genAiStudio: true
      modelAsService: true
      observabilityDashboard: true

    defaultWorkbenchPvcSize: 20Gi
    showJupyterInEnabledApplications: true

  selfSignedCerts: {}

  workloadScalingApp:
    installPlanApproval: *installPlanApproval
    kueue: *kueue
    trainer: *trainer
