apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hardware-management
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    name: in-cluster
    namespace: openshift-gitops
  source:
    path: helm/hardware-management
    repoURL: https://github.com/redhat-ai-americas/rhoai-argo.git
    targetRevision: gpu-app-breakout
    helm:
      parameters:
        - name: "global.installPlanApproval"
          value: {{ ((.Values.global) | default dict).installPlanApproval | default "Manual" | quote }}
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false 
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops