apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-operators
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: default
  source:
    path: helm/network-fabric
    repoURL: https://github.com/redhat-ai-americas/rhoai-argo.git
    targetRevision: gpu-app-breakout
    helm:
      parameters:
        - name: rhoaiChannel
          value: "fast-3.x"
        - name: "global.installPlanApproval"
          value: {{ .Values.global.installPlanApproval | default "Manual" | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops