{{- with .Values.dataScienceClusterInitialization }}
apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  name: default-dsci
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "31"
spec:
  monitoring:
    namespace: {{ .monitoring.namespace }}
    {{- if $.Values.enableObservabilityApp }}
    managementState: Managed
    metrics:
      {{- toYaml .monitoring.metrics | nindent 6 }}
    traces:
      {{- toYaml .monitoring.traces | nindent 6 }}
    {{- else }}
    managementState: Removed
    {{- end }}
{{- end }}
