channel: "stable"
operatorReplicas: 1
dashboardReplicas: 1
advancedServing: &advancedServing "Removed"

dataScienceCluster:
  create: true

  components:
    codeflare:
      managementState: Removed
    kserve:
      managementState: Managed
      nim:
        managementState: Managed
      defaultDeploymentMode: RawDeployment
      rawDeploymentServiceConfig: Headed
      serving:
        ingressGateway:
          certificate:
            type: OpenshiftDefaultIngress
        managementState: *advancedServing
        name: knative-serving
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    trustyai:
      managementState: Managed
    ray:
      managementState: Managed
    kueue:
      managementState: Managed
    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks
    dashboard:
      managementState: Managed
    modelmeshserving:
      managementState: Removed
    datasciencepipelines:
      managementState: Managed
    trainingoperator:
      managementState: Managed
    llamastackoperator:
      managementState: Managed

userGroups:
  - system:authenticated

dashboardConfig: {}

defaultWorkbenchPvcSize: 20Gi
showJupyterInEnabledApplications: true
notebookIdleCulling:
  enabled: true
  timeoutInMinutes: 240

modelServerSizes:
  - name: Small
    resources:
      limits:
        cpu: "2"
        memory: 8Gi
      requests:
        cpu: "1"
        memory: 4Gi
  - name: Medium
    resources:
      limits:
        cpu: "8"
        memory: 10Gi
      requests:
        cpu: "4"
        memory: 8Gi
  - name: Large
    resources:
      limits:
        cpu: "10"
        memory: 20Gi
      requests:
        cpu: "6"
        memory: 16Gi

notebookSizes:
  - name: Small
    resources:
      limits:
        cpu: "2"
        memory: 8Gi
      requests:
        cpu: "1"
        memory: 8Gi
  - name: Medium
    resources:
      limits:
        cpu: "6"
        memory: 24Gi
      requests:
        cpu: "3"
        memory: 24Gi
  - name: Large
    resources:
      limits:
        cpu: "14"
        memory: 56Gi
      requests:
        cpu: "7"
        memory: 56Gi
  - name: X Large
    resources:
      limits:
        cpu: "30"
        memory: 120Gi
      requests:
        cpu: "15"
        memory: 120Gi