apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  resourceHealthChecks:
    # This makes the Parent wait for the Child's status
    - group: argoproj.io
      kind: Application
      check: |
        hs = {}
        hs.status = "Healthy"
        if obj.status ~= nil and obj.status.health ~= nil then
          hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
        end
        return hs
    - group: operators.coreos.com
      kind: Subscription
      check: |
        hs = {}
        if obj.status ~= nil and obj.status.installedCSV ~= nil then
          hs.status = "Healthy"
          hs.message = "Operator installed"
        else
          hs.status = "Progressing"
          hs.message = "Waiting for CSV"
        end
        return hs
---
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  plugins:
    - gitops-plugin