apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  resourceHealthChecks:
    - group: operators.coreos.com
      kind: Subscription
      check: |
        hs = {}
        hs.status = "Progressing"
        hs.message = "Waiting for Operator installation to complete"
        if obj.status ~= nil then
          if obj.status.installedCSV ~= nil then
            hs.status = "Healthy"
            hs.message = "Operator is installed"
            return hs
          end
          if obj.status.state == "AtLatestKnown" then
            hs.status = "Healthy"
            hs.message = "Operator is at latest known state"
            return hs
          end
        end
        return hs
---
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  plugins:
    - gitops-plugin